services:
  - type: web
    name: academiamatch
    env: python
    buildCommand: "pip install -r requirements.txt && python load_data.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: SECRET_KEY
        generateValue: true
